### ISSUE TITLE
Remediation With issues

### ISSUE THREAD

**Issue by Daxx23** [MSEndpointMgr/CloudLAPS#12]
Hi, 

I implemented CloudLAPS and everything seems to be working smoothly.

But in Intune under Proactive remediation on my test systems is always says Detection status With issues and Remediation status Recurred.

Is this by design? I would expect Detection status to say Without issues.

**Comment by NickolajA** [comment]
It is unfortunately by design, as per how Microsoft has built the Proactive Remediation feature. When detection.ps1 triggers remediations.ps1, it's reported back that there was "an issue", hence why you're seeing that. Nothing really I can do about it, since the IME engine behind the scenes needs to interpret the exit codes to trigger remediation.ps1.
