### ISSUE TITLE
estimated azure costs

### ISSUE THREAD

**Issue by shortyhp622** [MSEndpointMgr/CloudLAPS#42]
Hi, we've a customer with about 3000 clients and want to use cloud laps. We've tested it, and it is perfect for our demand. Can you help us to estimate the costs for the azure services. We want to change the local admin password once a day.  Can you say anything about the costs .. only round about?

**Comment by nashein** [comment]
@shortyhp622 Have you estimated the costs, can you share it? I'm also looking for answer since we have more than 8000+ devices.

**Comment by shortyhp622** [comment]
no. but i found this closed issue which helped a lot https://github.com/MSEndpointMgr/CloudLAPS/issues/25

**Comment by JankeSkanke** [comment]
The cost is mainly driven by the Azure function plan you choose vs Number of executions. If you only have a small number of devices you could look into the consumption plan instead of Premium plans. On the Consumption plan, instances of the Functions host are dynamically added and removed based on the number of incoming events.
✔ Pay only when your functions are running.

Have a look here for more information about the plans:
[https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale?WT.mc_id=EM-MVP-5002085)
